---
--- Generated by Luanalysis
--- Created by jc.
--- DateTime: 2022/5/8 17:23
---


-- 1. 参数列表
-- 1 1 优惠券id
local voucherId = ARGV[1]
-- 1 2 用户id
local userId = ARGV[2]
-- 1 3 订单id
local orderId = ARGV[3]

-- 2 数据key
-- 2 1 库存key
local stockKey = 'jcwang-common:seckill:stock:' .. voucherId
-- 2 2 订单id，保存的是购买了这个优惠券的所有用户的id
local orderKey = 'jcwang-common:seckill:order:' .. voucherId

-- 3 脚本业务
-- 3 1 判断库存是否充足
if (tonumber(redis.call("get", stockKey)) <= 0) then
    -- 不足，返回1
    return 1
end

--3 2 判断用户是否下过单，即看orderKey中是否有这个用户了
if (redis.call("sismember", orderKey, userId) == 1) then
    -- 存在，说明重复下过单，返回2
    return 2
end


-- 3 4 扣库存
redis.call("incrby", stockKey, -1)
-- 3 5 下单（保存用户）
redis.call("sadd", orderKey, userId)

-- 3 6认定有资格后，向队列发送消息 XADD stream.orders * k1 v1 k2 v2
redis.call("xadd", "stream.orders", "*", "userId", userId, "voucherId", voucherId, "id", orderId);

return 0








